# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        language: [java, java_comp, c_sharp, c_sharp_comp, js, python, ruby]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Install Maven
        run: sudo apt-get install -y maven
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      - name: Set up .NET core
        run: |
          sudo apt-get install -y dotnet-sdk-7.0
      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.1
      - name: Download npm dependencies
        run: |
          cd src/test/JavaScript; npm install; cd -
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install pipenv
        run: |
          pip3 install --user pipenv
      - name: Download python dependencies
        run: |
          pipenv install
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Download ruby dependencies
        run: |
          cd src/test/Ruby; bundle install
      # Launch the tests
      - name: Launch Java Test
        run: pipenv run python telemetry.py
        env:
          TARGET_LANGUAGE: ${{ matrix.language }}
      - name: Upload test result artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-run
          path: |
            *.csv
      - name: Clean up; delete already uploaded csv files
        run: |
          rm *.csv
